[build]
target = "avr-specs/avr-atmega328p.json"
# remove on toolchain update
# https://github.com/rust-lang/cargo/issues/7433
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -cb 57600 -P /dev/ttyUSB0"

[unstable]
build-std = ["core"]
